"""empty message

Revision ID: 131e2907064a
Revises: 9b40306c49cf
Create Date: 2024-11-20 16:03:34.524727

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '131e2907064a'
down_revision = '9b40306c49cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hexagon',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('q', sa.Integer(), nullable=False),
    sa.Column('r', sa.Integer(), nullable=False),
    sa.Column('position', sa.Boolean(), nullable=False),
    sa.Column('target', sa.Boolean(), nullable=False),
    sa.Column('ally', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scenario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('scenario_number', sa.Integer(), nullable=False),
    sa.Column('gold', sa.Integer(), nullable=False),
    sa.Column('metal', sa.Integer(), nullable=False),
    sa.Column('lumber', sa.Integer(), nullable=False),
    sa.Column('hide', sa.Integer(), nullable=False),
    sa.Column('axenut', sa.Integer(), nullable=False),
    sa.Column('flamefruit', sa.Integer(), nullable=False),
    sa.Column('corpsecap', sa.Integer(), nullable=False),
    sa.Column('rockroot', sa.Integer(), nullable=False),
    sa.Column('arrowvine', sa.Integer(), nullable=False),
    sa.Column('snowthistle', sa.Integer(), nullable=False),
    sa.Column('random_item', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('scenario_number')
    )
    op.create_table('boss',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('scenario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenario.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('loot_deck',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scenario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('monster',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('scenario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenario.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('boss_action',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('boss_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('intiative', sa.Integer(), nullable=False),
    sa.Column('action_1', sa.String(length=120), nullable=False),
    sa.Column('action_2', sa.String(length=120), nullable=True),
    sa.Column('action_3', sa.String(length=120), nullable=True),
    sa.Column('action_4', sa.String(length=120), nullable=True),
    sa.Column('shuffle', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['boss_id'], ['boss.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('boss_stat_block',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('boss_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('life', sa.Integer(), nullable=False),
    sa.Column('damage', sa.Integer(), nullable=False),
    sa.Column('movement', sa.Integer(), nullable=False),
    sa.Column('special_effects', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['boss_id'], ['boss.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event_loot_card',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=120), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('event_one', sa.Float(), nullable=False),
    sa.Column('event_two', sa.Float(), nullable=False),
    sa.Column('event_three', sa.Float(), nullable=False),
    sa.Column('event_four', sa.Float(), nullable=False),
    sa.Column('event_five', sa.Float(), nullable=False),
    sa.Column('event_six', sa.Float(), nullable=False),
    sa.Column('event_seven', sa.Float(), nullable=False),
    sa.Column('event_eight', sa.Float(), nullable=False),
    sa.Column('event_nine', sa.Float(), nullable=False),
    sa.Column('event_ten', sa.Float(), nullable=False),
    sa.Column('loot_deck_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['loot_deck_id'], ['loot_deck.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('loot_card',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=120), nullable=False),
    sa.Column('two_player', sa.Integer(), nullable=False),
    sa.Column('three_player', sa.Integer(), nullable=False),
    sa.Column('four_player', sa.Integer(), nullable=False),
    sa.Column('loot_deck_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['loot_deck_id'], ['loot_deck.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('monster_action',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('monster_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('intiative', sa.Integer(), nullable=False),
    sa.Column('action_1', sa.String(length=120), nullable=False),
    sa.Column('action_2', sa.String(length=120), nullable=True),
    sa.Column('action_3', sa.String(length=120), nullable=True),
    sa.Column('action_4', sa.String(length=120), nullable=True),
    sa.Column('shuffle', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['monster_id'], ['monster.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('monster_stat_block',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('monster_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('life', sa.Integer(), nullable=False),
    sa.Column('elite_life', sa.Integer(), nullable=False),
    sa.Column('damage', sa.Integer(), nullable=False),
    sa.Column('elite_damage', sa.Integer(), nullable=False),
    sa.Column('movement', sa.Integer(), nullable=False),
    sa.Column('elite_movement', sa.Integer(), nullable=False),
    sa.Column('special_effects', sa.String(length=120), nullable=True),
    sa.Column('elite_special_effects', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['monster_id'], ['monster.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('boss_action_hexagon',
    sa.Column('boss_action_id', sa.Integer(), nullable=False),
    sa.Column('hexagon_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['boss_action_id'], ['boss_action.id'], ),
    sa.ForeignKeyConstraint(['hexagon_id'], ['hexagon.id'], ),
    sa.PrimaryKeyConstraint('boss_action_id', 'hexagon_id')
    )
    op.create_table('monster_action_hexagon',
    sa.Column('monster_action_id', sa.Integer(), nullable=False),
    sa.Column('hexagon_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['hexagon_id'], ['hexagon.id'], ),
    sa.ForeignKeyConstraint(['monster_action_id'], ['monster_action.id'], ),
    sa.PrimaryKeyConstraint('monster_action_id', 'hexagon_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('monster_action_hexagon')
    op.drop_table('boss_action_hexagon')
    op.drop_table('monster_stat_block')
    op.drop_table('monster_action')
    op.drop_table('loot_card')
    op.drop_table('event_loot_card')
    op.drop_table('boss_stat_block')
    op.drop_table('boss_action')
    op.drop_table('monster')
    op.drop_table('loot_deck')
    op.drop_table('boss')
    op.drop_table('scenario')
    op.drop_table('hexagon')
    # ### end Alembic commands ###
