"""empty message

Revision ID: 36d14458e9a5
Revises: 131e2907064a
Create Date: 2024-11-21 11:21:54.137600

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36d14458e9a5'
down_revision = '131e2907064a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('type_loot_deck',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=120), nullable=False),
    sa.Column('loot_deck_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['loot_deck_id'], ['loot_deck.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('type')
    )
    with op.batch_alter_table('event_loot_card', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type_loot_deck_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('event_loot_card_loot_deck_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'type_loot_deck', ['type_loot_deck_id'], ['id'])
        batch_op.drop_column('loot_deck_id')

    with op.batch_alter_table('loot_card', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type_loot_deck_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('loot_card_loot_deck_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'type_loot_deck', ['type_loot_deck_id'], ['id'])
        batch_op.drop_column('loot_deck_id')

    with op.batch_alter_table('loot_deck', schema=None) as batch_op:
        batch_op.drop_constraint('loot_deck_scenario_id_fkey', type_='foreignkey')
        batch_op.drop_column('scenario_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loot_deck', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scenario_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('loot_deck_scenario_id_fkey', 'scenario', ['scenario_id'], ['id'])

    with op.batch_alter_table('loot_card', schema=None) as batch_op:
        batch_op.add_column(sa.Column('loot_deck_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('loot_card_loot_deck_id_fkey', 'loot_deck', ['loot_deck_id'], ['id'])
        batch_op.drop_column('type_loot_deck_id')

    with op.batch_alter_table('event_loot_card', schema=None) as batch_op:
        batch_op.add_column(sa.Column('loot_deck_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('event_loot_card_loot_deck_id_fkey', 'loot_deck', ['loot_deck_id'], ['id'])
        batch_op.drop_column('type_loot_deck_id')

    op.drop_table('type_loot_deck')
    # ### end Alembic commands ###
