"""empty message

Revision ID: 56ec5f4ec595
Revises: fc2cc7f26174
Create Date: 2024-11-21 12:20:47.063309

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56ec5f4ec595'
down_revision = 'fc2cc7f26174'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_loot_card', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type_loot_deck_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'type_loot_deck', ['type_loot_deck_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_loot_card', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('type_loot_deck_id')

    # ### end Alembic commands ###
