"""empty message

Revision ID: fc2cc7f26174
Revises: 36d14458e9a5
Create Date: 2024-11-21 11:37:42.762373

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc2cc7f26174'
down_revision = '36d14458e9a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_loot_card', schema=None) as batch_op:
        batch_op.drop_constraint('event_loot_card_type_loot_deck_id_fkey', type_='foreignkey')
        batch_op.drop_column('type_loot_deck_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_loot_card', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type_loot_deck_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('event_loot_card_type_loot_deck_id_fkey', 'type_loot_deck', ['type_loot_deck_id'], ['id'])

    # ### end Alembic commands ###
