export const hound = {
  name: "Hound",
  maxNumber: 6,
  level0: {
    maxHp: 4,
    speed: 3,
    attack: 2,
    shield: 0,
    retaliate: {
      amount: 0,
      range: 0,
    },
    pierce: 0,
    statuses: [],
    elite: {
      maxHp: 6,
      speed: 5,
      attack: 2,
      shield: 0,
      retaliate: {
        amount: 0,
        range: 0,
      },
      pierce: 0,
      statuses: [],
    },
  },
  level1: {
    maxHp: 4,
    speed: 4,
    attack: 2,
    shield: 0,
    retaliate: {
      amount: 1,
      range: 1,
    },
    pierce: 0,
    statuses: [],
    elite: {
      maxHp: 6,
      speed: 5,
      attack: 2,
      shield: 0,
      retaliate: {
        amount: 2,
        range: 1,
      },
      pierce: 0,
      statuses: [],
    },
  },
  level2: {
    maxHp: 6,
    speed: 4,
    attack: 2,
    shield: 0,
    retaliate: {
      amount: 1,
      range: 1,
    },
    pierce: 0,
    statuses: [],
    elite: {
      maxHp: 7,
      speed: 5,
      attack: 3,
      shield: 0,
      retaliate: {
        amount: 2,
        range: 1,
      },
      pierce: 0,
      statuses: [],
    },
  },
  level3: {
    maxHp: 8,
    speed: 4,
    attack: 2,
    shield: 0,
    retaliate: {
      amount: 1,
      range: 1,
    },
    pierce: 0,
    statuses: [],
    elite: {
      maxHp: 8,
      speed: 5,
      attack: 4,
      shield: 0,
      retaliate: {
        amount: 2,
        range: 1,
      },
      pierce: 0,
      statuses: [],
    },
  },
  level4: {
    maxHp: 9,
    speed: 4,
    attack: 3,
    shield: 0,
    retaliate: {
      amount: 1,
      range: 1,
    },
    pierce: 0,
    statuses: [],
    elite: {
      maxHp: 11,
      speed: 5,
      attack: 4,
      shield: 0,
      retaliate: {
        amount: 2,
        range: 1,
      },
      pierce: 0,
      statuses: [],
    },
  },
  level5: {
    maxHp: 10,
    speed: 4,
    attack: 3,
    shield: 0,
    retaliate: {
      amount: 2,
      range: 1,
    },
    pierce: 0,
    statuses: [],
    elite: {
      maxHp: 13,
      speed: 5,
      attack: 4,
      shield: 0,
      retaliate: {
        amount: 3,
        range: 1,
      },
      pierce: 0,
      statuses: [],
    },
  },
  level6: {
    maxHp: 14,
    speed: 5,
    attack: 3,
    shield: 0,
    retaliate: {
      amount: 2,
      range: 1,
    },
    pierce: 0,
    statuses: [],
    elite: {
      maxHp: 17,
      speed: 6,
      attack: 5,
      shield: 0,
      retaliate: {
        amount: 3,
        range: 1,
      },
      pierce: 0,
      statuses: [],
    },
  },
  level7: {
    maxHp: 17,
    speed: 5,
    attack: 4,
    shield: 0,
    retaliate: {
      amount: 2,
      range: 1,
    },
    pierce: 0,
    statuses: [],
    elite: {
      maxHp: 23,
      speed: 6,
      attack: 6,
      shield: 0,
      retaliate: {
        amount: 3,
        range: 1,
      },
      pierce: 0,
      statuses: [],
    },
  },
  monsterDeck: [
    {
      name: "Nothing Special",
      step1: {
        type: "move",
        value: 0,
        pierce: null,
        status: null,
        range: null,
        targets: null,
        special_condition: null,
        special_condition_true: null,
      },
      step2: {
        type: "attack",
        value: 0,
        pierce: 0,
        status: null,
        range: 1,
        targets: 1,
        special_condition: null,
        special_condition_true: null,
      },
      step3: null,
      step4: null,
      shuffle: false,
      priority: 26,
    },
    {
      name: "Nothing Special",
      step1: {
        type: "move",
        value: 0,
        pierce: null,
        status: null,
        range: null,
        targets: null,
        special_condition: null,
        special_condition_true: null,
      },
      step2: {
        type: "attack",
        value: 0,
        pierce: 0,
        status: null,
        range: 1,
        targets: 1,
        special_condition: null,
        special_condition_true: null,
      },
      step3: null,
      step4: null,
      shuffle: false,
      priority: 26,
    },
    {
      name: "Pack Hunting",
      step1: {
        type: "move",
        value: 0,
        pierce: null,
        status: null,
        range: null,
        targets: null,
        special_condition: null,
        special_condition_true: null,
      },
      step2: {
        type: "attack",
        value: 0,
        pierce: 0,
        status: null,
        range: 1,
        targets: 1,
        special_condition: {
          description:
            "Add +2 attack if the target is adjacent to any of the Hound's allies",
          question: "Is hound adjacent to an ally?",
          true: {
            type: "attack",
            value: 2,
          },
          false: {
            type: "attack",
            value: 0,
          },
        },
        special_condition_true: null,
      },
      step3: null,
      step4: null,
      shuffle: true,
      priority: 19,
    },
    {
      name: "Pack Hunting",
      step1: {
        type: "move",
        value: 0,
        pierce: null,
        status: null,
        range: null,
        targets: null,
        special_condition: null,
        special_condition_true: null,
      },
      step2: {
        type: "attack",
        value: 0,
        pierce: 0,
        status: null,
        range: 1,
        targets: 1,
        special_condition: {
          description:
            "Add +2 attack if the target is adjacent to any of the Hound's allies",
          question: "Is the target adjacent to another enemy?",
          true: {
            type: "attack",
            value: 2,
          },
          false: {
            type: "attack",
            value: 0,
          },
        },
        special_condition_true: null,
      },
      step3: null,
      step4: null,
      shuffle: true,
      priority: 19,
    },
    {
      name: "Sharp Fangs",
      step1: {
        type: "attack",
        value: -1,
        pierce: 2,
        status: null,
        range: 1,
        targets: 1,
        special_condition: null,
        special_condition_true: null,
      },
      step2: {
        type: "move",
        value: -2,
        pierce: null,
        status: null,
        range: null,
        targets: null,
        special_condition: null,
        special_condition_true: null,
      },
      step3: {
        type: "attack",
        value: -1,
        pierce: 2,
        status: null,
        range: 1,
        targets: 1,
        special_condition: null,
        special_condition_true: null,
      },
      step4: null,
      shuffle: false,
      priority: 72,
    },
    {
      name: "Gripping Teeth",
      step1: {
        type: "move",
        value: -1,
        pierce: null,
        status: null,
        range: null,
        targets: null,
        special_condition: null,
        special_condition_true: null,
      },
      step2: {
        type: "attack",
        value: 0,
        pierce: 0,
        status: ["immobilize"],
        range: 1,
        targets: 1,
        special_condition: null,
        special_condition_true: null,
      },
      step3: null,
      step4: null,
      shuffle: false,
      priority: 6,
    },
    {
      name: "Harrowing Howl",
      step1: {
        type: "move",
        value: 0,
        pierce: 0,
        status: null,
        range: null,
        targets: null,
        special_condition: null,
        special_condition_true: null,
      },
      step2: {
        type: "attack",
        value: 0,
        pierce: 0,
        status: ["muddle"],
        range: 1,
        targets: "all",
        special_condition: null,
        special_condition_true: null,
      },
      step3: null,
      step4: null,
      shuffle: false,
      priority: 7,
    },
    {
      name: "Calculated Strike",
      step1: {
        type: "move",
        value: -2,
        pierce: null,
        status: null,
        range: null,
        targets: null,
        special_condition: null,
        special_condition_true: null,
      },
      step2: {
        type: "attack",
        value: 1,
        pierce: 0,
        status: null,
        range: 1,
        targets: 1,
        special_condition: null,
        special_condition_true: null,
      },
      step3: null,
      step4: null,
      shuffle: false,
      priority: 83,
    },
  ],
};
